### ISSUE TITLE
虚拟机里GUI一片空白，是虚拟化什么的不支持吗？

### ISSUE THREAD

**Issue by txl263** [libnyanpasu/clash-nyanpasu#1878]
### 复现步骤 / Step to reproduce

虚拟机里GUI一片空白，是虚拟化什么的不支持吗？

clash-nyanpasu v1.6.1 (Release Build)

╭─────────────────────────────── Build Information ───────────────────────────────╮
│   Commit Info: 07312702907e7cb459427f41dc7fd2b1bd270e6b by github-actions[bot]  │
│   Commit Time: 1 month ago (2024-09-07T16:09:54.000Z)                           │
│    Build Time: 1 month ago (2024-09-07T16:51:41.917Z)                           │
│  Build Target: x86_64-unknown-linux-gnu                                         │
│  Rust Version: rustc 1.83.0-nightly (26b5599e4 2024-09-06)                      │
│  LLVM Version: 19.1                                                             │
╰─────────────────────────────────────────────────────────────────────────────────╯

### 预期行为 / Expected behavior

GUI显示正常

### 实际行为 / Actual behavior

GUI一片空白

![image](https://github.com/user-attachments/assets/59c6b9ce-d8a2-445c-9894-60f9868d72e5)

### 环境信息 / Environment information

❯ uname -a
Linux myArch 6.11.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux

![image](https://github.com/user-attachments/assets/fd27cd54-e45d-458f-a652-e7162f00606c)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
1. 这个问题与虚拟机并无关联；
2. 看上去后端能够运行，前端可能出现了错误，请下载pre release检查dev tools中的报错

**Comment by MC-XiaoHei** [comment]
合理怀疑一下环境，试着重新安装libwebgtk？

**Comment by txl263** [comment]
> 1. 这个问题与虚拟机并无关联；
> 2. 看上去后端能够运行，前端可能出现了错误，请下载pre release检查dev tools中的报错

今天发现是wayland环境显示正常，X11显示空白。
然后系统滚动更新以后现在两个环境都不能运行了。。。

**Comment by greenhat616** [comment]
有尝试过 WEBKIT_DISABLE_DMABUF_RENDERER 吗

**Comment by txl263** [comment]
> WEBKIT_DISABLE_DMABUF_RENDERER

现在是 WEBKIT_DISABLE_DMABUF_RENDERER=0  依然是wayland环境显示正常，X11环境无法启动。

**Comment by greenhat616** [comment]
修改为 `WEBKIT_DISABLE_DMABUF_RENDERER=1`

**Comment by txl263** [comment]
真机上存在同样的问题，第一次启动的时候弹出这个
![image](https://github.com/user-attachments/assets/9c211239-6e84-462e-98ba-06809c63ee7f)
然后启动就没有任何反应了

**Comment by greenhat616** [comment]
> 真机上存在同样的问题，第一次启动的时候弹出这个 ![image](https://private-user-images.githubusercontent.com/969317/383084192-9c211239-6e84-462e-98ba-06809c63ee7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTk2OTgsIm5iZiI6MTczMDc5OTM5OCwicGF0aCI6Ii85NjkzMTcvMzgzMDg0MTkyLTljMjExMjM5LTZlODQtNDYyZS05OGJhLTA2ODA5YzYzZWU3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwOTM2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDJiZjE5YzM0NWFiYWYxMDE3MjUxZDkzMjFiM2ZkNmI0ZDVhNzM5MDc5ZjFjNjJhNjQ5ODMyZDc3MTNiZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RJl3Fdz-a63P-fv8DpohbIS-cJ69nHYrGzAnTInCFhA) 然后启动就没有任何反应了

这个错误似乎是因为你的系统未安装相关的托盘库导致。未提供日记不能详细判断，但可以证明这个和你之前提及的错误不是同一个问题。

此外，以下是我本机测试 AppImage 和 Deb 的结果

![image](https://github.com/user-attachments/assets/27c55271-942a-4dfb-b8a1-678e1c69c14c)
![image](https://github.com/user-attachments/assets/135ff97b-dd54-4927-9a58-ae32af856fba)
![image](https://github.com/user-attachments/assets/036f2c52-9008-4cbd-aa17-a98eb8f76daa)

**Comment by greenhat616** [comment]
白屏问题请参考之前的讨论：https://github.com/libnyanpasu/clash-nyanpasu/issues/685

**Comment by greenhat616** [comment]
另外，本机测试开发版也应正常启动的：
![image](https://github.com/user-attachments/assets/e6951c76-3ca6-4176-a0bc-5d87af7d391a)

如果遇到 panic dialog 请提供日记，非常感谢。

**Comment by txl263** [comment]
> 修改为 `WEBKIT_DISABLE_DMABUF_RENDERER=1`
不行，现在两个环境都不能启动了。

> 如果遇到 panic dialog 请提供日记，非常感谢。
我现在收集不到log，配置目录没有生成log文件，命令行没有输出。。。

**Comment by txl263** [comment]
> 真机上存在同样的问题，第一次启动的时候弹出这个 ![image](https://private-user-images.githubusercontent.com/969317/383084192-9c211239-6e84-462e-98ba-06809c63ee7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTM3NTAsIm5iZiI6MTczMjgxMzQ1MCwicGF0aCI6Ii85NjkzMTcvMzgzMDg0MTkyLTljMjExMjM5LTZlODQtNDYyZS05OGJhLTA2ODA5YzYzZWU3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNzA0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWJkNjM1M2UxNTc5MzE2MTMyZGQ1YzAwOWI1M2YyY2ZhNjdmYWZjZGNmMzg2NmZhOTVkZTYzYTgyODZhZTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wINkppcazpw81eqH7YjQf4WKslWlZAgtL2oE3U1ynQQ) 然后启动就没有任何反应了

真机上又不能启动了，每次都弹上面这个弹窗。
按提示获取的log
```
UST_BACKTRACE=1 clash-nyanpasu
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.7.2/src/app/tray.rs:610:5:
item id not found
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tauri::app::tray::SystemTrayHandle<R>::get_item
   3: clash_nyanpasu::core::tray::Tray::update_part
   4: clash_nyanpasu::core::tray::Tray::update_systray
   5: clash_nyanpasu::utils::resolve::resolve_setup
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
   7: tauri::app::Builder<R>::build
   8: clash_nyanpasu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
RUST_BACKTRACE=full clash-nyanpasu
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.7.2/src/app/tray.rs:610:5:
item id not found
stack backtrace:
   0:     0x56880246ba89 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h589e65cc8b61d31e
   1:     0x568801e7999b - core::fmt::write::h85feaca529ba6ce1
   2:     0x5688024308d2 - std::io::Write::write_fmt::hb87087d89092487e
   3:     0x56880246f992 - std::sys::backtrace::BacktraceLock::print::h4189ea7435230bb3
   4:     0x56880246f7e7 - std::panicking::default_hook::{{closure}}::h88178407ef4f6ab9
   5:     0x56880246f578 - std::panicking::default_hook::h3ccc334e12568011
   6:     0x568801aaa5e6 - clash_nyanpasu::main::{{closure}}::he042271ca7fa4d90
   7:     0x56880246fc9c - std::panicking::rust_panic_with_hook::h2fbc7848bd138bf1
   8:     0x56880246fa52 - std::panicking::begin_panic_handler::{{closure}}::hc439499884a4b219
   9:     0x56880246f9e9 - std::sys::backtrace::__rust_end_short_backtrace::hcc71b0742078f0c0
  10:     0x56880246f9d4 - rust_begin_unwind
  11:     0x568801e77f32 - core::panicking::panic_fmt::hbf678bbc126bd0af
  12:     0x5688018ec436 - tauri::app::tray::SystemTrayHandle<R>::get_item::h87b53013cba7ed1a
  13:     0x568801ad8402 - clash_nyanpasu::core::tray::Tray::update_part::h592a4993defa7ef0
  14:     0x568801ad7ad6 - clash_nyanpasu::core::tray::Tray::update_systray::h089d1ae8f3531c06
  15:     0x568801a96c70 - clash_nyanpasu::utils::resolve::resolve_setup::h5dfb8aadb52a2615
  16:     0x56880185a805 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3e50f524a5d30da4
  17:     0x5688018e71a8 - tauri::app::Builder<R>::build::hd90042875dee12b3
  18:     0x568801aa92eb - clash_nyanpasu::main::hf76e0d63ffdf8cdc
  19:     0x56880182efe8 - std::sys::backtrace::__rust_begin_short_backtrace::h1abb311e49578006
  20:     0x568801afef43 - main
  21:     0x78fd69834e08 - <unknown>
  22:     0x78fd69834ecc - __libc_start_main
  23:     0x5688017011a5 - _start
  24:                0x0 - <unknown>
```

**Comment by Shouren** [comment]
遇到了同样的问题,有解决方法么目前
