### ISSUE TITLE
无法打开控制面板

### ISSUE THREAD

**Issue by ShawnRn** [LibNyanpasu/clash-nyanpasu#569]
### 复现步骤 / Step to reproduce

安装 - 打开 - 右键尝试打开控制面板 - 无法打开，显示“Something went wrong:(”
具体报错内容如下：
Something went wrong:(
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
Error Stack
Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at l (https://tauri.localhost/assets/index-Qa1PUXZC.js:341:7490)
    at connect (https://tauri.localhost/assets/index-Qa1PUXZC.js:341:7683)
    at https://tauri.localhost/assets/index-Qa1PUXZC.js:341:11023
    at R5 (https://tauri.localhost/assets/index-Qa1PUXZC.js:40:24335)
    at tw (https://tauri.localhost/assets/index-Qa1PUXZC.js:40:42567)
    at WOe (https://tauri.localhost/assets/index-Qa1PUXZC.js:40:41387)
    at w0 (https://tauri.localhost/assets/index-Qa1PUXZC.js:40:40424)
    at qie (https://tauri.localhost/assets/index-Qa1PUXZC.js:40:37004)
    at Vv (https://tauri.localhost/assets/index-Qa1PUXZC.js:38:3302)
    at tw (https://tauri.localhost/assets/index-Qa1PUXZC.js:40:42709)

### 预期行为 / Expected behaviour

控制面板应该正常打开

### 实际行为 / Actual Behaviour

未能正确显示控制面板页面
![Snipaste_2024-03-07_10-33-31](https://github.com/LibNyanpasu/clash-nyanpasu/assets/114976385/baadf7dc-faf7-4cd1-a848-fda827e9c448)

### 应用日志 / App logs

[clash-nyanpasu.2024-03-07.app.log](https://github.com/LibNyanpasu/clash-nyanpasu/files/14518016/clash-nyanpasu.2024-03-07.app.log)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11 23H2 22631.3235

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
你的日记是空白都。请修改 app log level 后，将带有调试信息的日记提交上来。

**Comment by ShawnRn** [comment]
> 你的日记是空白的。请修改 app log level 后，将带有调试信息的日记提交上来。

打不开面板就没办法修改Log Level
![Uploading A959A7B612035ABFFB13EF2EC4BE03A8.png…]()

**Comment by greenhat616** [comment]
直接修改配置文件，目录在用户目录.config/clash-nyanpasu 下，字段改为 debug








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年3月7日(周四) 中午12:31写道:

  

  
你的日记是空白的。请修改 app log level 后，将带有调试信息的日记提交上来。
  
打不开面板就没办法修改Log Level

**Comment by greenhat616** [comment]
文档已更新，请按要求更新日记等级，然后提交日记，谢谢！
<https://nyanpasu.elaina.moe/zh-CN/others/faq.html#_2-clash-nyanpasu-%E5%BA%94%E7%94%A8-%E6%97%A5%E8%AE%B0%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C>

**Comment by 4o3F** [comment]
当前版本将外部控制改为127.0.0.1即可解决，更好的解决方案之后我们会实现

**Comment by ShawnRn** [comment]
> 当前版本将外部控制改为127.0.0.1即可解决，更好的解决方案之后我们会实现

好的 感谢耐心解决

**Comment by greenhat616** [comment]
问题相关：https://github.com/tauri-apps/tauri/issues/3007 https://github.com/clash-verge-rev/clash-verge-rev/issues/92

**Comment by greenhat616** [comment]
拟计划实现 TCP 反向代理，解决这个问题
